### ISSUE TITLE
App starts at boot even when Autostart is disabled.

### ISSUE THREAD

**Issue by pm-pm** [blokadaorg/blokada#456]
# Steps to reproduce
1. Set "settings/autostart" to **OFF**
2. Set "Werbesperre" (on first page) to **ON**
3. Reboot phone
4. App is activ.

### Expected behaviour
No start of applikation

### Actual behaviour
Applikation starts, even when autostart is disabled.

### Configuration
1. Blokada version: 4.1.4
2. Device model: Moto 5
3. Android version / ROM: Stock version 8.1

Please stop starting the app after reboot when autostart is set to off!

**Comment by rpeter85** [comment]
Just to be sure, can you check if "Always-ON VPN" is enabled in the system's settings?

**Comment by pm-pm** [comment]
What do you mean exactly with "Always-ON VPN"? There is no point like this in settings.

I have a menu option on the first page "VPN einrichten (configure)" and this is "off" because i have no VPN connection configured.

Is that what you mean?

**Comment by rpeter85** [comment]
System settings - Network & Internet - VPN - Blokada / gear - Always-on VPN

**Comment by pm-pm** [comment]
My app 4.1.4 does not have these settings.
Will do a test with new app 4.1.6

**Comment by kar** [comment]
Fixed in 4p1p6, please confirm

**Comment by pm-pm** [comment]
Still the same situation. Blokada starts after **reboot** even when autostart is off.

Blokada starts after reboot with this settings:
```
Autostart: off
Blokada: on
VPN off (and i have no VPN account)
```

If 
```
Autostart: off
Blokada: _pause_
VPN off (and i have no VPN account)
```
then blokada does not start after reboot.

What's the point of switch "Autostart: off" then?

**Comment by kar** [comment]
Hm. do you have watchdog enabled?

**Comment by pm-pm** [comment]
No, Watchdog is set to off.
